# Generated by Django 6.0 on 2025-12-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student')], default='faculty', max_length=10),
        ),
    ]
